name: Hacktoberfest Leaderboard

on:
  pull_request:
    types: [closed]

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check if the PR was merged
      if: github.event.pull_request.merged == true
      run: echo "PR merged"

    - name: Set contributor points
      id: set_points
      run: |
        POINTS=5 # Default to small (5 points)
        if [[ $(echo "${{ github.event.pull_request.labels }}" | grep -q "medium") ]]; then
          POINTS=10
        elif [[ $(echo "${{ github.event.pull_request.labels }}" | grep -q "large") ]]; then
          POINTS=15
        fi
        echo "POINTS=$POINTS" >> $GITHUB_ENV # Replacing set-output with the recommended method

    - name: Get current leaderboard
      uses: actions/github-script@v6
      id: leaderboard
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue_number = 1;
          const repo_owner = 'galaxy-bytes';
          const repo_name = 'main-test-repo';
          
          const { data: issue } = await github.rest.issues.get({
            owner: repo_owner,
            repo: repo_name,
            issue_number: issue_number
          });
          
          return issue.body;

    - name: Update leaderboard
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const contributor = github.actor;
          const new_points = parseInt(process.env.POINTS); 
          const leaderboard = ${{ steps.leaderboard.outputs.result }};
          
          let updated_leaderboard = updateLeaderboard(contributor, new_points, leaderboard);

          await github.rest.issues.update({
            owner: 'galaxy-bytes',
            repo: 'main-test-repo',
            issue_number: 1,
            body: updated_leaderboard
          });

