name: Propagate Issue Labels to PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  copy_labels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get issue number from PR body
      id: issue_number
      run: |
        issue_number=$(echo "${{ github.event.pull_request.body }}" | grep -oP "(?<=#)\d+")
        echo "::set-output name=issue_number::$issue_number"

    - name: Get labels from linked issue
      if: steps.issue_number.outputs.issue_number != ''
      uses: actions/github-script@v6
      id: issue_labels
      with:
        script: |
          const issue_number = ${{ steps.issue_number.outputs.issue_number }};
          const { data: issue } = await github.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number
          });
          return issue.labels.map(label => label.name);

    - name: Add labels to PR
      if: steps.issue_number.outputs.issue_number != ''
      uses: actions/github-script@v6
      with:
        script: |
          const pr_number = context.issue.number;
          const labels = ${{ steps.issue_labels.outputs.result }};
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr_number,
            labels: labels
          });
